# apiVersion: v1
# data:
#   mapRoles: |
#     - groups:
#       - system:bootstrappers
#       - system:nodes
#       rolearn: arn:aws:iam::315069654700:role/eksctl-expense-1-nodegroup-expense-NodeInstanceRole-QpZ8MlrLGAdG
#       username: system:node:{{EC2PrivateDNSName}}
#   mapUsers: |
#     - groups:
#       - expense-pod-reader
#       userarn: arn:aws:iam::315069654700:user/harish
#       username: dev-raghu
# kind: ConfigMap
# metadata:
#   creationTimestamp: "2024-07-05T01:35:42Z"
#   name: aws-auth
#   namespace: kube-system
#   uid: eea0273c-8df3-4176-8901-b17003f83095 #don't delete this


#-------------------------------


apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::974145757135:role/node-group-2-eks-node-group-20260329121841958600000002
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::974145757135:role/node-group-1-eks-node-group-20260329121841959000000003
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - expense-pod-reader
        userarn: arn:aws:iam::974145757135:user/dev-raghu
        username: dev-raghu 
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-29T12:28:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1046"
  uid: 5b92b639-5a64-43d2-b537-fe27f79be4a8
