variable "aws_region" {}
variable "access_key" {}
variable "secret_key" {}
variable "vcp_cidr" {}
variable "subnet1a_cidr" {}
variable "subnet2b_cidr" {}
variable "subnet3c_cidr" {}
variable "ami_id" {}
variable  "instance_type" {}