apiVersion: v1
kind: Pod
metadata:
  name: db-pod
spec:
  containers:
  - name: nginx
    image: nginx

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: type
            operator: In
            values:
            - db

  tolerations:
  - key: "type"
    operator: "Equal"
    value: "db"
    effect: "NoSchedule"